### ISSUE TITLE
Support for AMD rx5700 cards

### ISSUE THREAD

**Issue by Jamesf1983** [nickbabcock/OhmGraphite#108]
Looking at LibreHardwareMonitor there was an issue where it did not return any data for rx5700s, so I assume this is why OhmGraphite does not return data on these cards. LibreHardwareMonitor has now been updated to resolve this (Issue linked below), is it possible to integrate this fix into OhmGraphite?

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/177

**Comment by nickbabcock** [comment]
Excellent! I took a look at this issue before I left for the airport. Usually it's a simple git submodule update, but it appears there has been some major refactoring in the last couple months. I'm worried that some of the renamed enums could cause broken dashboards. I believe the fix would be to have some translation layer to maintain backwards compatibility. I'm on holiday for the next couple weeks, but I'll get it done when I get back.
