### ISSUE TITLE
Ryzen 2 SoC voltages and temp offsets

### ISSUE THREAD

**Issue by aaronjwood** [nickbabcock/OhmGraphite#110]
Would be awesome if you could pull in the latest release to include [SoC voltage detection](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/95fdd4920dab0197dfa15d9a5369f9bc8f38efa3#diff-22ec6d72745e8ae95a2004b90f9abb9b) and [temp offset adjustments](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/d26dcc4189ecc3deeb390c41cddcb033530d863f#diff-22ec6d72745e8ae95a2004b90f9abb9b)!

**Comment by nickbabcock** [comment]
Awesome! Those changes will be incorporated once #112 is merged 😄
