### ISSUE TITLE
Not able to see CCD temps on a Zen 2 chip (3950x)

### ISSUE THREAD

**Issue by aaronjwood** [nickbabcock/OhmGraphite#123]
The latest version of LHM shows me my CCD temps like so:
![Capture](https://user-images.githubusercontent.com/446283/75096812-12da4980-5558-11ea-875c-421c86723539.PNG)
I'm not sure if this needs to be pulled out separately with some extra code or if the current .dll being used by this project doesn't support this but it would be super nice to be able report on the CCD temps. The only thing I can pull out right now is this:
![Capture](https://user-images.githubusercontent.com/446283/75096855-9d22ad80-5558-11ea-81d4-318dbb436874.PNG)
AFAIK the CCD temps (Tdie) are the actual temps at the dies, the Tctl/Tdie that's reported now are the actual temps with an offset applied which is not at all what I think most people would want to see.

**Comment by nickbabcock** [comment]
Yup, can confirm. Looks like CCD temps were added just a few days after the pinned version of LHM that OhmGraphite uses. Let me re-pin to the latest master, do a smoke test, and release a new version.

Thank you for the repot

**Comment by aaronjwood** [comment]
Awesome! Thanks for the quick response!

**Comment by nickbabcock** [comment]
This should be included in the recently released v0.12.0 version, let me know if it's not what you expect 👌

**Comment by aaronjwood** [comment]
Works great, thanks!
