### ISSUE TITLE
Not able to see CPU temperature on a i9-9880h

### ISSUE THREAD

**Issue by FLeven** [nickbabcock/OhmGraphite#143]
It is reported OHM, but not exposed by the exporter.

**Comment by nickbabcock** [comment]
Thanks for the bug report! Couple questions:

- Which version of OHM worked? Do you happen to know which version of OHM started exposing coffee lake refresh (eg: was it 0.9.0 or 0.9.1, etc)?
- [Does the latest build of LibreHardwareMonitor](https://ci.appveyor.com/project/LibreHardwareMonitor/librehardwaremonitor/build/artifacts) expose the i9-9880h?

**Comment by FLeven** [comment]
Only tested the latest OHM Version and the latest LHM also shows the temperatures

**Comment by FLeven** [comment]
OK, seems to be a OS related problem, when I start a different Windows 10 on my machine, all values are working and displayed unser metrics. CPU Temp/Core are not reported on the other Windows 10, maybe there is a service deactivated or some Lenovo Drivers are missing.
