### ISSUE TITLE
Cant login to influxDB

### ISSUE THREAD

**Issue by transguy4l80** [nickbabcock/OhmGraphite#166]
I have tried to login to Influxdb, I know that my login info is correct based on using the same info to login to telegraf. I am trying to log in from a windows server to a linux VM on a different machine both on the same vlan of the network in my homelab. Windows firewall and linux firewall are both disabled completely but the traffic is behind a pfsense router. Any ideas would be great. 

[OhmGraphite Logs.zip](https://github.com/nickbabcock/OhmGraphite/files/5322367/OhmGraphite.Logs.zip)

**Comment by transguy4l80** [comment]
Still not sure what was causing this issue however I was able to get it working by enabling a passwordless user and blank password

**Comment by nickbabcock** [comment]
Thank you for providing logs. What version of influxdb are you trying to write to?

**Comment by transguy4l80** [comment]
1.8

**Comment by nickbabcock** [comment]
Doing some sleuthing.

In the uploaded config I noticed the following is commented out:

```xml
<!--
    <add key="influx_user" value="admin" />
    <add key="influx_password" value="*********" />
    <add key="interval" value="15" />
-->
```

You're not accidentally commenting this out, right?

Also other influxdb users have similar errors:

 - https://github.com/influxdata/influxdb/issues/8967
 - https://github.com/influxdata/influxdb/issues/16678

**Comment by nickbabcock** [comment]
I'm going to assume this is resolved. Let me know if not.
