### ISSUE TITLE
Temperatures are not reported with Ryzen 5950x

### ISSUE THREAD

**Issue by Arderos** [nickbabcock/OhmGraphite#174]
With latest LibreHardwareMonitor the OhmGraphite is not detecting temperature sensors of Ryzen 5950x CPU:

Log: https://pastebin.com/FjgRiYjS

LHW screenshot:
![image](https://user-images.githubusercontent.com/12333169/100402852-60975b80-306e-11eb-9c5b-8f48070b5778.png)

**Comment by nickbabcock** [comment]
Thank you for the report. I'll work on incorporating the latest LibreHardwareMonitor changes and make a new release (hopefully within the next few days).
