### ISSUE TITLE
No power for nvidia gpu (it has worked for a while)

### ISSUE THREAD

**Issue by ikorbln** [nickbabcock/OhmGraphite#185]
Hello, i think after a couple driver updates from nvidia i did not get any power readings anymore for the gpu.
I the logfile there are all sorts of readings for load/clock but no power.

I use the latest version 0.16.
Nvidia is 460.89 / RTX3070

**Comment by nickbabcock** [comment]
Can you check if `%windir%/system32/nvml.dll` exists

Is the power readings present if you run the [latest version of LibreHardwareMonitor (at the time of writing)](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/suites/1634426889/artifacts/30185229)?

**Comment by ikorbln** [comment]
The dll is not in this directory and with the Libre there is no power reading for gpu.

**Comment by nickbabcock** [comment]
Hmm I would recommend reinstalling nvidia geforce or compiling nvml via some other means and placing it in that directory or alongside the ohmgraphite executable.

**Comment by ikorbln** [comment]
ok, after reinstalling the driver the nvml.dll is now in the folder but the Libre did not show the power.

**Comment by nickbabcock** [comment]
I'd next try restarting and then copying the nvml.dll to the same folder as Libre / OhmGraphite

**Comment by ikorbln** [comment]
sorry, no success. Last day i saw the gpu power in the ohmgraphite_log was the 8 Dec.

**Comment by nickbabcock** [comment]
I wonder what happened on December 8th.

**Comment by peterholmberg** [comment]
New user of your exporter and I'm also experiencing this. 

Running v.0.16 of Ohm and v.0.8.6 of libre. The power usage is not reported in any of them. Might be a change to the nvidia api?

**Comment by nickbabcock** [comment]
Good find. Looks like we may have to wait for nvidia to push this fix or have users download their hotfix

**Comment by nickbabcock** [comment]
Fixed in the latest nvidia driver update. After updating, restart ohmgraphite.
