### ISSUE TITLE
Question on network port utilization and the ability to enable only specific monitoring.

### ISSUE THREAD

**Issue by shatai1** [nickbabcock/OhmGraphite#227]
Hi there,

First off, this is an amazing tool, thank you for all your work on this :)

I've noticed that the process OhmGraphite has multiple open network connections as shown in screenshot, is this normal please?
![image](https://user-images.githubusercontent.com/85617845/122874867-ba8aa600-d35d-11eb-942a-8b416a148af0.png)

Is it possible to enable only specific sensor, say only CPU temperature? If yes how do I do that please? In telegraf, we can enable/disable specific counters in the conf. file as below, is there something similar in OhmGraphite please?

  [[inputs.win_perf_counters.object]]
    # Example query where the Instance portion must be removed to get data back,
    # such as from the Memory object.
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes",
      "Standby Cache Reserve Bytes",
      "Standby Cache Normal Priority Bytes",
      "Standby Cache Core Bytes",
    ]

Thank you very much for your kind support.

**Comment by nickbabcock** [comment]
Does the number of open connections grow over time, or is it always approximately 10? I'm not too concerned unless you find it poses an issue in which case we can find a solution.

[See how to hide sensors](https://github.com/nickbabcock/OhmGraphite#hiding-sensors) if you want to disable them.

**Comment by shatai1** [comment]
Hi there! Thank you so much for the quick reply :) I have a few more questions please.

Does Ohmgraphite support HTTPS? I have https enabled on my influxDB and getting the follow error in Ohmgraphite logs
![image](https://user-images.githubusercontent.com/85617845/122933385-cf385f80-d398-11eb-9094-ef26dccf7277.png)

Is the following the correct way to hide sensors?
![image](https://user-images.githubusercontent.com/85617845/122935220-5cc87f00-d39a-11eb-84a8-7618d5d4d2ae.png)

This is what's showing in my logs even after adding hidden suffix.
![image](https://user-images.githubusercontent.com/85617845/122934490-c3996880-d399-11eb-8a23-6e164c159632.png)

**Comment by nickbabcock** [comment]
> Does Ohmgraphite support HTTPS?

Yes: https://github.com/nickbabcock/OhmGraphite#certificates

> Is the following the correct way to hide sensors?

Yes that looks correct, the log lines that you see represent more that the sensor was detected, but your hidden line should stop the those sensors from reporting data into influxdb.

**Comment by shatai1** [comment]
Thanks for the confirmation!

Do you have any thoughts on why I may be getting the following error please?

![image](https://user-images.githubusercontent.com/85617845/123046376-3b14d980-d426-11eb-988a-1efda68a74c9.png)

I have tried all of the following, still no luck, the certificate is self-signed.

![image](https://user-images.githubusercontent.com/85617845/123048040-2b969000-d428-11eb-90af-89055e7122a0.png)

![image](https://user-images.githubusercontent.com/85617845/123048060-318c7100-d428-11eb-88d6-320dbaf0885c.png)

![image](https://user-images.githubusercontent.com/85617845/123048464-a2cc2400-d428-11eb-8dc5-85757572f4d4.png)

**Comment by nickbabcock** [comment]
Sorry, I am unable to reproduce. Feel free to include reproducible steps (eg: cert generation + docker commands)

**Comment by shatai1** [comment]
No worries and thank you so much for your kind help support so far :)  I'll have HTTPS disabled for now.

One more question in regards to hiding sensor please.  At the moment the following sensors are discovered on my laptop.

![image](https://user-images.githubusercontent.com/85617845/123267152-e5742600-d526-11eb-8342-a103dc04931f.png)

As I am planning to deploy OhmGraphite on several machines, each machine would have different NIC id, is it possible to use something equivalent to wildcard "*" to hide the NIC as against to having to provide the exact NIC ID please?

![image](https://user-images.githubusercontent.com/85617845/123267188-ed33ca80-d526-11eb-9cf8-2c083d50f33a.png)

**Comment by nickbabcock** [comment]
That is a good idea, let me think about how that can be done.

**Comment by shatai1** [comment]
Thank you Nick, really appreciate all your help! Hope to hear some good news soon :)

**Comment by nickbabcock** [comment]
Can you confirm that this artifact from PR #229 implements this suggestion to your satisfaction? https://github.com/nickbabcock/OhmGraphite/suites/3084649803/artifacts/70404608

**Comment by shatai1** [comment]
Hi Nick, yes! Works great now!  Thank you so much for this, you're awesome!
