### ISSUE TITLE
Latest version reports 0% GPU Fan

### ISSUE THREAD

**Issue by Tualua** [nickbabcock/OhmGraphite#250]
![image](https://user-images.githubusercontent.com/32481693/138032248-03fd0e70-c11c-4ce9-b1c1-348ada9ca9ac.png)

![image](https://user-images.githubusercontent.com/32481693/138032301-cd9fa36d-7803-4206-8aad-ab718f1207bd.png)

**Comment by Tualua** [comment]
Hmmm, it works on GTX 1070

![image](https://user-images.githubusercontent.com/32481693/138201061-71491409-2a70-4834-ad7b-ac89ed53e9cb.png)

**Comment by nickbabcock** [comment]
It's a little tough to follow the investigation. Kinda looks like it is still an upstream issue (regression?) with LibreHardwareMonitor. Or is it elsewhere?
