### ISSUE TITLE
Prometheus hostname label

### ISSUE THREAD

**Issue by namxam** [nickbabcock/OhmGraphite#260]
From what I have found in the issues, it should be possible to somehow read the instances hostname. But when I look at the metrics, there is nothing exposing it. I also tried to force it by adding `<add key="name_lookup" value="my-cool-machine" />` to my config and restarted the service. But no luck.

Am I doing something wrong or is it not supported with prometheus?

BTW… awesome tool. I was trying lots of alternatices but nothing was as easy and polished as your solution. I really love it!

**Comment by nickbabcock** [comment]
Hey, glad you like it!

With prometheus it's not as straightforward to get the hostname. Prometheus [automatically creates the instance label when scraping](https://prometheus.io/docs/concepts/jobs_instances/). So what you really want to do is [change the instance label](https://www.robustperception.io/controlling-the-instance-label) by either hardcoding the alias in the config or using DNS.

I know it's confusing, so I'll update the docs to mention that `name_lookup` is has not effect when using prometheus.
