### ISSUE TITLE
PSU (Corsair RM750i) sensors appear in LHM but not in OhmGraphite

### ISSUE THREAD

**Issue by arturhgca** [nickbabcock/OhmGraphite#277]
Hi!

Thank you very much for your work on this tool, it's working great for my use case! However, there is one piece of hardware that isn't being detected by OhmGraphite (v0.23.1), even though it appears in LHM (v0.8.9): my Corsair RM750i PSU.

This is what LHM shows:

![image](https://user-images.githubusercontent.com/29523470/149672730-913bcb4e-e631-4ad8-a5b4-0b2b7b18e628.png)

I've checked the OhmGraphite logs and there are no sensors matching these (but other sensors in the system are fine). This is my config:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="type" value="influx2" />
    <add key="influx2_address" value="http://localhost:8086" />
    <add key="influx2_org" value="omitted" />
    <add key="influx2_bucket" value="omitted" />
    <add key="influx2_token" value="omitted" />
    <add key="interval" value="5" />
  </appSettings>
</configuration>
```

I have also tried removing all keys from the config, but that changed nothing regarding sensors.

Any idea of what might be happening?

Thanks!

**Comment by nickbabcock** [comment]
Thanks for the reporting this issue. Would you like to try out [the build](https://github.com/nickbabcock/OhmGraphite/suites/4954656669/artifacts/143934746) from #278 and see if that fixes your issue?

**Comment by arturhgca** [comment]
Sure thing, on it. Thanks for the quick response!

**Comment by arturhgca** [comment]
@nickbabcock the new build works! I can see the sensors being added in the logs and in InfluxDB.

**Comment by nickbabcock** [comment]
Glad to hear. You can keep using that nightly build and the next release will include this functionality.
