### ISSUE TITLE
Grafana cloud support

### ISSUE THREAD

**Issue by notariuss** [nickbabcock/OhmGraphite#296]
Hello! Can you please provide support to allow put credentials for grafana cloud?

**Comment by nickbabcock** [comment]
Can you elaborate? [Based on the documentation](https://grafana.com/docs/grafana-cloud/fundamentals/gs-metrics/#store-query-and-alert-on-data), I don't think OhmGraphite would send data directly to Grafana cloud. Instead Grafana cloud works with a data source like influxdb, graphite, or prometheus.

Or are you talking about the provided dashboard templates? These should be already accessible in grafana cloud and doesn't require credentials
