### ISSUE TITLE
running latest but missing ohm_hdd_bytes

### ISSUE THREAD

**Issue by phynias** [nickbabcock/OhmGraphite#298]
loaded latest ohm and dashboard. the dash has some graphs that use ohm_hdd_bytes, but i don't see that in prometheus.

**Comment by nickbabcock** [comment]
I believe there's a regression in the underlying sensor library, LibreHardwareMonitor. Do you have a samsung nvme drive (ie: a 980 PRO)? If so, I'll fix the issue upstream and make another release.

**Comment by phynias** [comment]
no, mushkin reactor ssd

**Comment by nickbabcock** [comment]
Bummer, if you run the [LibreHardwareMonitor GUI](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor#where-can-i-download-it) do you see values for data read / data written for you ssd? If not, then it looks like it may be an issue with properly detecting these values in LibreHardwareMonitor

**Comment by phynias** [comment]
looks ok in there.
![Capture](https://user-images.githubusercontent.com/10147213/173211206-070e4be2-ab81-4601-9a47-67e688ce4de1.PNG)

**Comment by nickbabcock** [comment]
Yeah looks like your hard drive isn't exposing any data fields

![image](https://user-images.githubusercontent.com/2106129/173237467-c63903b1-e4de-4db3-946e-f9487b292561.png)

This is why the `ohm_hdd_bytes` graphs are blank as they are rely on the data sensors.

**Comment by phynias** [comment]
ahh ok. weird none of my drives have a data section.
