### ISSUE TITLE
aquacomputer highflow next sensor

### ISSUE THREAD

**Issue by EnlightedBitFox** [nickbabcock/OhmGraphite#314]
Hey,
is there a way how to get the sensor data from aquacomputer highflow next sensor in OhmGraphite?

**Comment by nickbabcock** [comment]
The aqua computer sensors should be enabled by default. Do you not see them if you use LibreHardwareMonitor directly? https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases

**Comment by EnlightedBitFox** [comment]
Unfortunately not.
![grafik](https://user-images.githubusercontent.com/79202835/194546752-6c5c3583-69cc-4d76-b7fe-c3cc27bf1356.png)

**Comment by nickbabcock** [comment]
Ah bummer, well the first step would be to raise an issue in the LibreHardwareMonitor repo to add support for the highflow sensor. Then once it has been added upstream, it'll be exposed in ohmgraphite.

**Comment by EnlightedBitFox** [comment]
> Ah bummer, well the first step would be to raise an issue in the LibreHardwareMonitor repo to add support for the highflow sensor. Then once it has been added upstream, it'll be exposed in ohmgraphite.

ok. I did opend an issue in the LibreHardwareMonitor repo. 
Lets see what happens.
Thx anyway

**Comment by EnlightedBitFox** [comment]
So, now after nearly a month nothing cames around from the LibreHardwareMonitor repo.

have you any idea how i can fix it or continue?

**Comment by nickbabcock** [comment]
I release OhmGraphite v0.34, which updates LibreHardwareMonitor to include high flow sensor changes: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1268

Let me know if this doesn't fix the issue.
