### ISSUE TITLE
Network load

### ISSUE THREAD

**Issue by lfpoulain** [nickbabcock/OhmGraphite#34]
I can't see any network load in Grafana, so I guess it's not send by OhmGraphit. Is it possible to add it in the futur ? 
Regards

**Comment by nickbabcock** [comment]
The network plugin has been sub-optimal until recently, so yes I'll enable it in OhmGraphite shortly. I'll cut a release within 7 days if everything is still stable. Sound good?

**Comment by lfpoulain** [comment]
Sounds great ! Thanks 💯

**Comment by nickbabcock** [comment]
[v0.8.0](https://github.com/nickbabcock/OhmGraphite/releases/tag/v0.8.0) has been released with network sensors. Enjoy 😄
