### ISSUE TITLE
dashboard for influx not working 

### ISSUE THREAD

**Issue by Kalimeiro** [nickbabcock/OhmGraphite#346]
Hi,

Import into Grafana for use the dashboard with influx database isn't working, it create correctly row and panel, but each panel doesn't have influx query.

I'm using latest version of Grafana/InfluxDB and OhmGraphite.

Thanks.

**Comment by nickbabcock** [comment]
I just confirmed setting up a new ohmgraphite influxql dashboard with influx 2.6 that everything appears working. Please dig into the problem, and let me know the details if further help is needed.

**Comment by Kalimeiro** [comment]
Hi,

Your confirmation is impossible, in your readme.md you specify this link to start dashboard using influxdb : https://grafana.com/grafana/dashboards/11601

And clearly, it's not working because it's for the older version of InfluxDB.

Thanks.

**Comment by ausghostdog** [comment]
@Kalimeiro following this https://youtu.be/gEIgg5zHuIU?t=1282, I was having the same issue my self, you need to link the bucket in influx 2+ to a db for v1 

![image](https://github.com/nickbabcock/OhmGraphite/assets/7588602/e8e8c0f2-6ea5-4857-b42d-51ca96d77a74)
proof I have it working
