### ISSUE TITLE
Windows 11 22H2 cannot monitor temperature.

### ISSUE THREAD

**Issue by Fancy-World** [nickbabcock/OhmGraphite#365]
Hello master, my os version is: Windows 11 22H2 (22621.1413). When I start OhmGraphite and access "ipAddress+port/metrics" in the browser, I find that there is no ohm_cpu_celsius and prometheus can’t monitor the temperature either.

**Comment by nickbabcock** [comment]
I'd try the [desktop version](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor#where-can-i-download-it) and see if you see cpu temperature. If you don't see temperature there either, then it is an upstream issue (so feel free to file a bug report there).

**Comment by nickbabcock** [comment]
Feel free to report a status update. In the meantime, I'll close out this issue.
