### ISSUE TITLE
SSL on Prometheus mode.

### ISSUE THREAD

**Issue by roy-spark** [nickbabcock/OhmGraphite#377]
I can't find any way to setup TLS for a metrics endpoint.

I would gladly contribute since I want some other features such as certain metrics on HDD levels that today are available in windows exporter. But I would rather only run one exporter per windows server.

**Comment by nickbabcock** [comment]
Based on https://github.com/prometheus-net/prometheus-net/issues/237, it might be pretty low effort to add this feature if most the setup is on the OS level (relevant line to change): https://github.com/nickbabcock/OhmGraphite/blob/da63a2efa473935e2f3db9fe443876dc24768eaf/OhmGraphite/Program.cs#L114).

I'd definitely accept this contribution
