### ISSUE TITLE
Ability to change metrics path for prometheus in configuration.

### ISSUE THREAD

**Issue by roy-spark** [nickbabcock/OhmGraphite#387]
Ability to change Prometheus export path url. e.g. from `hostname/metrics` to `hostname/3fGS3gCs`
At the moment it is hard coded. Path from config file can be restricted and therefore validated by urlsafe base64 - or exception is thrown.

I am well aware that this is _security by obfuscation_ but it is used by multutide by enterprise integrations for Prometheus (see for instance [Unity Exceptions Prometheus Exporter](https://docs.unity.com/cloud-diagnostics-advanced/en/manual/MetricsExporter#Promethe)).

This trick is great for situations where it is difficult to monitor the network by non-wanted users. It is also a common way as shown above.

**Comment by nickbabcock** [comment]
Yeah looks like it would be possible to pass in a custom path through the prometheus server constructor

https://github.com/nickbabcock/OhmGraphite/blob/4ccb5199870cf4001faaf810f3033dd97794b132/OhmGraphite/Program.cs#L114

I'm fine with this suggestion.
