### ISSUE TITLE
Connect to existing LibreHardwareMonitor instance?

### ISSUE THREAD

**Issue by shalak** [nickbabcock/OhmGraphite#395]
I'm running LHW minimized to tray 24/7. I'm using it via WMI Query to read some data used in other services.

If I understand correctly, installing OhwmGraphite will install it's own LHW instance, right? Thus I'll have two LHW running on my machine.

Is it possible to connect OhmGraphite to the LWH instance that I'm already running on my host?

**Comment by nickbabcock** [comment]
That's an interesting idea. What is the concern with running two instances of LHW? 

It may be possible for the datasource that OhmGraphite exports to to be the source of truth instead of running two instances.

**Comment by shalak** [comment]
> What is the concern with running two instances of LHW?

performance & unnecessary bloat

> It may be possible for the datasource that OhmGraphite exports to to be the source of truth instead of running two instances.

Yep, that's probably what I'll end up with, I just need to refactor some of my workflows. I was hoping that there might be a way to avoid it :)

**Comment by nickbabcock** [comment]
I'm going to close the issue as this feature isn't planned at this time. But I'm happy to continue the discussion if there's compelling reasons.
