### ISSUE TITLE
Modification to the influx dashboard

### ISSUE THREAD

**Issue by ausghostdog** [nickbabcock/OhmGraphite#397]
So I swithed from Graphite to using influx due to wanting to monitor another system that used influx, if you are going to use a newer Influx version as in 2.0 + then you need to setup one last thing for you https://grafana.com/grafana/dashboards/11601-ohm-influx/ to work with the newer influx

In influx 2.0 DBs are called buckets so you need to link a bucket id to a db as shown in the image below
![image](https://github.com/nickbabcock/OhmGraphite/assets/7588602/2744cc79-c6c5-497b-abd3-80c35ae300c3)

I found this using 
https://www.youtube.com/watch?v=gEIgg5zHuIU
can see this is working for me 
![image](https://github.com/nickbabcock/OhmGraphite/assets/7588602/0ddf173b-591c-4426-a3a3-9d6e1b961905)

**Comment by nickbabcock** [comment]
I'm not sure I quite understand the issue. Is this a configuring an influxdb data source connection in grafana issue?
