### ISSUE TITLE
"ohm_gpuati_factor" doesn't report data with AMD driver 23.12.1

### ISSUE THREAD

**Issue by Kybeer** [nickbabcock/OhmGraphite#427]
I just updated my AMD driver from 23.11.1 to 23.12.1, and noticed the the `ohm_gpuati_factor` FPS metric is no longer repoting anything.

It doesn't appear at all if I check my Prometheus endpoint http://localhost:4445/metrics. I don't know if anything can be done on OhmGraphite side, or if it's a driver issue. I'm on v0.31.0 (latest right now).

All other metrics looks fine.

**Comment by nickbabcock** [comment]
- Restarting the computer may be worth trying if you haven't already.
- I'd be curious if you see the sensor listed in the GUI https://github.com/LibreHardwareMonitor/LibreHardwareMonitor#where-can-i-download-it  (if not, we're looking at an upstream issue).

**Comment by Kybeer** [comment]
> * Restarting the computer may be worth trying if you haven't already.
> 
>     * I'd be curious if you see the sensor listed in the GUI https://github.com/LibreHardwareMonitor/LibreHardwareMonitor#where-can-i-download-it  (if not, we're looking at an upstream issue).

Restarting makes no difference. 

The value is visible in LibreHardwareMontor still:

![image](https://github.com/nickbabcock/OhmGraphite/assets/57593336/5bd6deeb-e226-41ef-a060-c71c3b4a2bea)

**Comment by nickbabcock** [comment]
Thank you for checking. The plot thickens. Can you try running OhmGraphite interactively?

```pwsh
./OhmGraphite stop
./OhmGraphite run
```

A few have reported that doing this can yield more metrics and I'm curious if this is one of those cases.

**Comment by Kybeer** [comment]
> Thank you for checking. The plot thickens. Can you try running OhmGraphite interactively (in an adminstrator terminal)?
> 
> ```powershell
> ./OhmGraphite stop
> ./OhmGraphite run
> ```
> 
> A few have reported that doing this can yield more metrics and I'm curious if this is one of those cases.

Thanks for your time on this. I did what you suggested but it makes no difference. The terminal shows a log of metrics and the fps is still always 0 (line 69), just like the Prometheus endpoint. I attached the terminal output as text here. 

[ohm.txt](https://github.com/nickbabcock/OhmGraphite/files/13692347/ohm.txt)

Since this happened after a driver update perhaps its reporting FPS in a new way? On the other hand running LibreHardwareMontor still shows it correct...

**Comment by nickbabcock** [comment]
To clarify, is the fps being reported as zero or not reported at all?

The sensor is being detected so that is good. My hunch is that if you were to flip on debug logging https://github.com/nickbabcock/OhmGraphite#debugging-tips there may be more log lines related to the faulty sensor.

**Comment by Kybeer** [comment]
> To clarify, is the fps being reported as zero or not reported at all?
> 
> The sensor is being detected so that is good. My hunch is that if you were to flip on debug logging https://github.com/nickbabcock/OhmGraphite#debugging-tips there may be more log lines related to the faulty sensor.

Actually, `ohm_gpuati_factor{sensor="Fullscreen FPS"}` doesnt' return any data at all. The metric is not even appearing in the Prometheus endpoint (http://localhost:4445/metrics)

**Comment by nickbabcock** [comment]
In the log posted earlier, I saw the following snippet:

```
Sensor added: /gpu-amd/0/factor/0 "Fullscreen FPS"
```

When you switched to debug logging, were there more lines related to `/gpu-amd/0/factor/0`?

**Comment by Kybeer** [comment]
> Fullscreen FPS

I enabled Debug but I don't think there's much difference. Attaching the log file here.

**Comment by nickbabcock** [comment]
The mystery deepens! I see `/gpu-amd/0/factor/0` listed in the first log but not in the second. What do you think changed?

**Comment by Kybeer** [comment]
> The mystery deepens! I see `/gpu-amd/0/factor/0` listed in the first log but not in the second. What do you think changed?

I haven't changed anything myself since the driver update three weeks ago. There's been Windows updates in that time though..

**Comment by nickbabcock** [comment]
Still scratching my head a bit. Thank you for your patience

Try the [OhmGraphite artifact](https://github.com/nickbabcock/OhmGraphite/actions/runs/7386059504) from the [PR that bumps to LibreHardwareMonitor 0.9.3](https://github.com/nickbabcock/OhmGraphite/pull/433)

Probably also worth double checking the [official release of LibreHardwareMonitor 0.9.3](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.9.3) still shows everything correctly too.

**Comment by Kybeer** [comment]
> Still scratching my head a bit. Thank you for your patience

Hi again. Driver 24.1.1 dropped today and FPS is now working again :)

![image](https://github.com/nickbabcock/OhmGraphite/assets/57593336/801d9cb0-002f-41b6-8a52-1f4d9bd6387e)

**Comment by nickbabcock** [comment]
That's great news, I'll go ahead and close this issue out.
