### ISSUE TITLE
Integrated GPU sensors displaces Discrete GPU sensors

### ISSUE THREAD

**Issue by meandrii** [nickbabcock/OhmGraphite#451]
Having two GPUs Integrate + Discrete, cause software to pull tempurate from Integrated on the Discrete Graph

I disabled Integrated AMD GPU in Device Manager and looks like graphite started to pull correct data; take a look at the graph
Orange arrow indicates the moment of disabling integrated graphics

I use latest version of software with default config, except Prometheus integration.
My hardware is:
CPU:7800X3D
GPU:RX6950XT

![Screenshot 2024-09-08 233417](https://github.com/user-attachments/assets/6fe80caf-004f-4b3b-ba0d-d541daa13d2b)
![Screenshot 2024-09-08 233424](https://github.com/user-attachments/assets/de276a63-9e9e-48cc-b0cb-0cbd354c513b)

Data from http://localhost:4445/metrics
Both GPUs enabled:
```
# HELP ohm_gpuati_celsius Metric reported by open hardware sensor
# TYPE ohm_gpuati_celsius gauge
ohm_gpuati_celsius{hardware="AMD Radeon RX 6950 XT",sensor="GPU VR SoC",hw_instance="5"} 40
ohm_gpuati_celsius{hardware="AMD Radeon(TM) Graphics",sensor="GPU VR SoC",hw_instance="1"} 40
```
Only discrete GPU enabled:
```
# HELP ohm_gpuati_celsius Metric reported by open hardware sensor
# TYPE ohm_gpuati_celsius gauge
ohm_gpuati_celsius{hardware="AMD Radeon RX 6950 XT",sensor="GPU Hot Spot",hw_instance="10"} 56
ohm_gpuati_celsius{hardware="AMD Radeon RX 6950 XT",sensor="GPU Core",hw_instance="10"} 52
```

**Comment by nickbabcock** [comment]
Thanks for the bug report. Can you try out the latest nightly build of LibreHardwareMonitor (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor?tab=readme-ov-file#where-can-i-download-it)

That'll let us know where the bug is coming from.

**Comment by meandrii** [comment]
New build is on the right, and looks good to me.
![Screenshot 2024-09-09 132833](https://github.com/user-attachments/assets/76464be6-f91d-4e7c-b170-2fdc06383509)

**Comment by nickbabcock** [comment]
Nice, can you try out the latest build of ohmgraphite? (it's a zip file found here: https://github.com/nickbabcock/OhmGraphite/actions/runs/10783732414?pr=452 )

If it works, I'll cut a new version of OhmGraphite in the next couple days.

**Comment by meandrii** [comment]
I think there are a problem with powe nowr, freq and temperature for integrated not correct
And i am not sure for Discrete
![Screenshot 2024-09-09 224935](https://github.com/user-attachments/assets/5c30d535-fb07-4c2e-8c21-2418624ac6ad)
![Screenshot 2024-09-09 224955](https://github.com/user-attachments/assets/caf747b6-9a1e-4ff1-9b49-21d59411599a)
![Screenshot 2024-09-09 225008](https://github.com/user-attachments/assets/404d5b07-fd2c-4852-9e5d-5bdadb3ccdd4)
![Screenshot 2024-09-09 225132](https://github.com/user-attachments/assets/f899dda6-9e08-4698-936f-6865d7830ab2)

**Comment by nickbabcock** [comment]
Ah this might be a dashboard problem. I think I know what the problem is, but if you want to run a quick test:

Update the wattage dashboard so the metric is includes the hardware instance:

```
ohm_gpuati_watts{instance="$instance",hardware="$gpu"}
```

Does that solve the problem? You'd have to do it for each graph.

This should make it so the GPU metrics aren't stepping on each others toes.

If this works, I'll update the dashboard templates.
